//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line_Bot_Application2.ServiceAuthen {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAuthen.AuthenticationSoap")]
    public interface AuthenticationSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authenticate", ReplyAction="*")]
        Line_Bot_Application2.ServiceAuthen.AuthenticateResponse Authenticate(Line_Bot_Application2.ServiceAuthen.AuthenticateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authenticate", ReplyAction="*")]
        System.Threading.Tasks.Task<Line_Bot_Application2.ServiceAuthen.AuthenticateResponse> AuthenticateAsync(Line_Bot_Application2.ServiceAuthen.AuthenticateRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentDetails", ReplyAction="*")]
        Line_Bot_Application2.ServiceAuthen.GetStudentDetailsResponse GetStudentDetails(Line_Bot_Application2.ServiceAuthen.GetStudentDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<Line_Bot_Application2.ServiceAuthen.GetStudentDetailsResponse> GetStudentDetailsAsync(Line_Bot_Application2.ServiceAuthen.GetStudentDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStaffDetails", ReplyAction="*")]
        Line_Bot_Application2.ServiceAuthen.GetStaffDetailsResponse GetStaffDetails(Line_Bot_Application2.ServiceAuthen.GetStaffDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStaffDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<Line_Bot_Application2.ServiceAuthen.GetStaffDetailsResponse> GetStaffDetailsAsync(Line_Bot_Application2.ServiceAuthen.GetStaffDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserDetails", ReplyAction="*")]
        Line_Bot_Application2.ServiceAuthen.GetUserDetailsResponse GetUserDetails(Line_Bot_Application2.ServiceAuthen.GetUserDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<Line_Bot_Application2.ServiceAuthen.GetUserDetailsResponse> GetUserDetailsAsync(Line_Bot_Application2.ServiceAuthen.GetUserDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStaffID", ReplyAction="*")]
        Line_Bot_Application2.ServiceAuthen.GetStaffIDResponse GetStaffID(Line_Bot_Application2.ServiceAuthen.GetStaffIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStaffID", ReplyAction="*")]
        System.Threading.Tasks.Task<Line_Bot_Application2.ServiceAuthen.GetStaffIDResponse> GetStaffIDAsync(Line_Bot_Application2.ServiceAuthen.GetStaffIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authenticate", Namespace="http://tempuri.org/", Order=0)]
        public Line_Bot_Application2.ServiceAuthen.AuthenticateRequestBody Body;
        
        public AuthenticateRequest() {
        }
        
        public AuthenticateRequest(Line_Bot_Application2.ServiceAuthen.AuthenticateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AuthenticateRequestBody() {
        }
        
        public AuthenticateRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Line_Bot_Application2.ServiceAuthen.AuthenticateResponseBody Body;
        
        public AuthenticateResponse() {
        }
        
        public AuthenticateResponse(Line_Bot_Application2.ServiceAuthen.AuthenticateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AuthenticateResult;
        
        public AuthenticateResponseBody() {
        }
        
        public AuthenticateResponseBody(bool AuthenticateResult) {
            this.AuthenticateResult = AuthenticateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentDetails", Namespace="http://tempuri.org/", Order=0)]
        public Line_Bot_Application2.ServiceAuthen.GetStudentDetailsRequestBody Body;
        
        public GetStudentDetailsRequest() {
        }
        
        public GetStudentDetailsRequest(Line_Bot_Application2.ServiceAuthen.GetStudentDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetStudentDetailsRequestBody() {
        }
        
        public GetStudentDetailsRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Line_Bot_Application2.ServiceAuthen.GetStudentDetailsResponseBody Body;
        
        public GetStudentDetailsResponse() {
        }
        
        public GetStudentDetailsResponse(Line_Bot_Application2.ServiceAuthen.GetStudentDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Line_Bot_Application2.ServiceAuthen.ArrayOfString GetStudentDetailsResult;
        
        public GetStudentDetailsResponseBody() {
        }
        
        public GetStudentDetailsResponseBody(Line_Bot_Application2.ServiceAuthen.ArrayOfString GetStudentDetailsResult) {
            this.GetStudentDetailsResult = GetStudentDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStaffDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStaffDetails", Namespace="http://tempuri.org/", Order=0)]
        public Line_Bot_Application2.ServiceAuthen.GetStaffDetailsRequestBody Body;
        
        public GetStaffDetailsRequest() {
        }
        
        public GetStaffDetailsRequest(Line_Bot_Application2.ServiceAuthen.GetStaffDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStaffDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetStaffDetailsRequestBody() {
        }
        
        public GetStaffDetailsRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStaffDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStaffDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Line_Bot_Application2.ServiceAuthen.GetStaffDetailsResponseBody Body;
        
        public GetStaffDetailsResponse() {
        }
        
        public GetStaffDetailsResponse(Line_Bot_Application2.ServiceAuthen.GetStaffDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStaffDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Line_Bot_Application2.ServiceAuthen.ArrayOfString GetStaffDetailsResult;
        
        public GetStaffDetailsResponseBody() {
        }
        
        public GetStaffDetailsResponseBody(Line_Bot_Application2.ServiceAuthen.ArrayOfString GetStaffDetailsResult) {
            this.GetStaffDetailsResult = GetStaffDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserDetails", Namespace="http://tempuri.org/", Order=0)]
        public Line_Bot_Application2.ServiceAuthen.GetUserDetailsRequestBody Body;
        
        public GetUserDetailsRequest() {
        }
        
        public GetUserDetailsRequest(Line_Bot_Application2.ServiceAuthen.GetUserDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetUserDetailsRequestBody() {
        }
        
        public GetUserDetailsRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Line_Bot_Application2.ServiceAuthen.GetUserDetailsResponseBody Body;
        
        public GetUserDetailsResponse() {
        }
        
        public GetUserDetailsResponse(Line_Bot_Application2.ServiceAuthen.GetUserDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Line_Bot_Application2.ServiceAuthen.ArrayOfString GetUserDetailsResult;
        
        public GetUserDetailsResponseBody() {
        }
        
        public GetUserDetailsResponseBody(Line_Bot_Application2.ServiceAuthen.ArrayOfString GetUserDetailsResult) {
            this.GetUserDetailsResult = GetUserDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStaffIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStaffID", Namespace="http://tempuri.org/", Order=0)]
        public Line_Bot_Application2.ServiceAuthen.GetStaffIDRequestBody Body;
        
        public GetStaffIDRequest() {
        }
        
        public GetStaffIDRequest(Line_Bot_Application2.ServiceAuthen.GetStaffIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStaffIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetStaffIDRequestBody() {
        }
        
        public GetStaffIDRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStaffIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStaffIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Line_Bot_Application2.ServiceAuthen.GetStaffIDResponseBody Body;
        
        public GetStaffIDResponse() {
        }
        
        public GetStaffIDResponse(Line_Bot_Application2.ServiceAuthen.GetStaffIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStaffIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStaffIDResult;
        
        public GetStaffIDResponseBody() {
        }
        
        public GetStaffIDResponseBody(string GetStaffIDResult) {
            this.GetStaffIDResult = GetStaffIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthenticationSoapChannel : Line_Bot_Application2.ServiceAuthen.AuthenticationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationSoapClient : System.ServiceModel.ClientBase<Line_Bot_Application2.ServiceAuthen.AuthenticationSoap>, Line_Bot_Application2.ServiceAuthen.AuthenticationSoap {
        
        public AuthenticationSoapClient() {
        }
        
        public AuthenticationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Line_Bot_Application2.ServiceAuthen.AuthenticateResponse Line_Bot_Application2.ServiceAuthen.AuthenticationSoap.Authenticate(Line_Bot_Application2.ServiceAuthen.AuthenticateRequest request) {
            return base.Channel.Authenticate(request);
        }
        
        public bool Authenticate(string username, string password) {
            Line_Bot_Application2.ServiceAuthen.AuthenticateRequest inValue = new Line_Bot_Application2.ServiceAuthen.AuthenticateRequest();
            inValue.Body = new Line_Bot_Application2.ServiceAuthen.AuthenticateRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Line_Bot_Application2.ServiceAuthen.AuthenticateResponse retVal = ((Line_Bot_Application2.ServiceAuthen.AuthenticationSoap)(this)).Authenticate(inValue);
            return retVal.Body.AuthenticateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Line_Bot_Application2.ServiceAuthen.AuthenticateResponse> Line_Bot_Application2.ServiceAuthen.AuthenticationSoap.AuthenticateAsync(Line_Bot_Application2.ServiceAuthen.AuthenticateRequest request) {
            return base.Channel.AuthenticateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Line_Bot_Application2.ServiceAuthen.AuthenticateResponse> AuthenticateAsync(string username, string password) {
            Line_Bot_Application2.ServiceAuthen.AuthenticateRequest inValue = new Line_Bot_Application2.ServiceAuthen.AuthenticateRequest();
            inValue.Body = new Line_Bot_Application2.ServiceAuthen.AuthenticateRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Line_Bot_Application2.ServiceAuthen.AuthenticationSoap)(this)).AuthenticateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Line_Bot_Application2.ServiceAuthen.GetStudentDetailsResponse Line_Bot_Application2.ServiceAuthen.AuthenticationSoap.GetStudentDetails(Line_Bot_Application2.ServiceAuthen.GetStudentDetailsRequest request) {
            return base.Channel.GetStudentDetails(request);
        }
        
        public Line_Bot_Application2.ServiceAuthen.ArrayOfString GetStudentDetails(string username, string password) {
            Line_Bot_Application2.ServiceAuthen.GetStudentDetailsRequest inValue = new Line_Bot_Application2.ServiceAuthen.GetStudentDetailsRequest();
            inValue.Body = new Line_Bot_Application2.ServiceAuthen.GetStudentDetailsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Line_Bot_Application2.ServiceAuthen.GetStudentDetailsResponse retVal = ((Line_Bot_Application2.ServiceAuthen.AuthenticationSoap)(this)).GetStudentDetails(inValue);
            return retVal.Body.GetStudentDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Line_Bot_Application2.ServiceAuthen.GetStudentDetailsResponse> Line_Bot_Application2.ServiceAuthen.AuthenticationSoap.GetStudentDetailsAsync(Line_Bot_Application2.ServiceAuthen.GetStudentDetailsRequest request) {
            return base.Channel.GetStudentDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Line_Bot_Application2.ServiceAuthen.GetStudentDetailsResponse> GetStudentDetailsAsync(string username, string password) {
            Line_Bot_Application2.ServiceAuthen.GetStudentDetailsRequest inValue = new Line_Bot_Application2.ServiceAuthen.GetStudentDetailsRequest();
            inValue.Body = new Line_Bot_Application2.ServiceAuthen.GetStudentDetailsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Line_Bot_Application2.ServiceAuthen.AuthenticationSoap)(this)).GetStudentDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Line_Bot_Application2.ServiceAuthen.GetStaffDetailsResponse Line_Bot_Application2.ServiceAuthen.AuthenticationSoap.GetStaffDetails(Line_Bot_Application2.ServiceAuthen.GetStaffDetailsRequest request) {
            return base.Channel.GetStaffDetails(request);
        }
        
        public Line_Bot_Application2.ServiceAuthen.ArrayOfString GetStaffDetails(string username, string password) {
            Line_Bot_Application2.ServiceAuthen.GetStaffDetailsRequest inValue = new Line_Bot_Application2.ServiceAuthen.GetStaffDetailsRequest();
            inValue.Body = new Line_Bot_Application2.ServiceAuthen.GetStaffDetailsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Line_Bot_Application2.ServiceAuthen.GetStaffDetailsResponse retVal = ((Line_Bot_Application2.ServiceAuthen.AuthenticationSoap)(this)).GetStaffDetails(inValue);
            return retVal.Body.GetStaffDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Line_Bot_Application2.ServiceAuthen.GetStaffDetailsResponse> Line_Bot_Application2.ServiceAuthen.AuthenticationSoap.GetStaffDetailsAsync(Line_Bot_Application2.ServiceAuthen.GetStaffDetailsRequest request) {
            return base.Channel.GetStaffDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Line_Bot_Application2.ServiceAuthen.GetStaffDetailsResponse> GetStaffDetailsAsync(string username, string password) {
            Line_Bot_Application2.ServiceAuthen.GetStaffDetailsRequest inValue = new Line_Bot_Application2.ServiceAuthen.GetStaffDetailsRequest();
            inValue.Body = new Line_Bot_Application2.ServiceAuthen.GetStaffDetailsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Line_Bot_Application2.ServiceAuthen.AuthenticationSoap)(this)).GetStaffDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Line_Bot_Application2.ServiceAuthen.GetUserDetailsResponse Line_Bot_Application2.ServiceAuthen.AuthenticationSoap.GetUserDetails(Line_Bot_Application2.ServiceAuthen.GetUserDetailsRequest request) {
            return base.Channel.GetUserDetails(request);
        }
        
        public Line_Bot_Application2.ServiceAuthen.ArrayOfString GetUserDetails(string username, string password) {
            Line_Bot_Application2.ServiceAuthen.GetUserDetailsRequest inValue = new Line_Bot_Application2.ServiceAuthen.GetUserDetailsRequest();
            inValue.Body = new Line_Bot_Application2.ServiceAuthen.GetUserDetailsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Line_Bot_Application2.ServiceAuthen.GetUserDetailsResponse retVal = ((Line_Bot_Application2.ServiceAuthen.AuthenticationSoap)(this)).GetUserDetails(inValue);
            return retVal.Body.GetUserDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Line_Bot_Application2.ServiceAuthen.GetUserDetailsResponse> Line_Bot_Application2.ServiceAuthen.AuthenticationSoap.GetUserDetailsAsync(Line_Bot_Application2.ServiceAuthen.GetUserDetailsRequest request) {
            return base.Channel.GetUserDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Line_Bot_Application2.ServiceAuthen.GetUserDetailsResponse> GetUserDetailsAsync(string username, string password) {
            Line_Bot_Application2.ServiceAuthen.GetUserDetailsRequest inValue = new Line_Bot_Application2.ServiceAuthen.GetUserDetailsRequest();
            inValue.Body = new Line_Bot_Application2.ServiceAuthen.GetUserDetailsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Line_Bot_Application2.ServiceAuthen.AuthenticationSoap)(this)).GetUserDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Line_Bot_Application2.ServiceAuthen.GetStaffIDResponse Line_Bot_Application2.ServiceAuthen.AuthenticationSoap.GetStaffID(Line_Bot_Application2.ServiceAuthen.GetStaffIDRequest request) {
            return base.Channel.GetStaffID(request);
        }
        
        public string GetStaffID(string username, string password) {
            Line_Bot_Application2.ServiceAuthen.GetStaffIDRequest inValue = new Line_Bot_Application2.ServiceAuthen.GetStaffIDRequest();
            inValue.Body = new Line_Bot_Application2.ServiceAuthen.GetStaffIDRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Line_Bot_Application2.ServiceAuthen.GetStaffIDResponse retVal = ((Line_Bot_Application2.ServiceAuthen.AuthenticationSoap)(this)).GetStaffID(inValue);
            return retVal.Body.GetStaffIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Line_Bot_Application2.ServiceAuthen.GetStaffIDResponse> Line_Bot_Application2.ServiceAuthen.AuthenticationSoap.GetStaffIDAsync(Line_Bot_Application2.ServiceAuthen.GetStaffIDRequest request) {
            return base.Channel.GetStaffIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Line_Bot_Application2.ServiceAuthen.GetStaffIDResponse> GetStaffIDAsync(string username, string password) {
            Line_Bot_Application2.ServiceAuthen.GetStaffIDRequest inValue = new Line_Bot_Application2.ServiceAuthen.GetStaffIDRequest();
            inValue.Body = new Line_Bot_Application2.ServiceAuthen.GetStaffIDRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Line_Bot_Application2.ServiceAuthen.AuthenticationSoap)(this)).GetStaffIDAsync(inValue);
        }
    }
}
